PORTIFOLIO/AboutPage/routes.py
from flask import Blueprint, render_template

aboutPage = Blueprint('aboutPage', __name__)


@aboutPage.route("/About")
def aboutpage():
    return render_template("About.html")

PORTIFOLIO/ContactPage/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app
from flask_mail import Message
from PORTIFOLIO import mail

contactPage = Blueprint('contactPage', __name__)

@contactPage.route('/contact', methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        subject = request.form['subject']
        user_email = request.form['email']
        body = request.form['message']

        try:
            # Set a no-reply address as the sender
            no_reply_address = "no-reply@example.com"  # Replace with your no-reply address

            # Create the message
            msg = Message(subject, sender=no_reply_address, recipients=["karinna.rocha2@gmail.com"])
            msg.body = f"From: {user_email}\n\n{body}"

            # Set the reply-to to the user's email
            msg.reply_to = user_email

            # Send the email
            mail.send(msg)
            flash('Message sent successfully!')
        except Exception as e:
            flash(f'An error occurred: {str(e)}')
            print(f'Error: {str(e)}')

        return redirect(url_for('contactPage.contact'))
    
    return render_template('Contact.html')

PORTIFOLIO/IndexPage/routes.py
from flask import render_template, Blueprint

indexPage = Blueprint('indexPage', __name__)


@indexPage.route("/")
def home():
    return render_template("index.html")

PORTIFOLIO/WorkPage/routes.py
from flask import Blueprint, render_template

workPage = Blueprint('workPage', __name__)


@workPage.route("/Work")
def workpage():
    return render_template("Work.html")

PORTIFOLIO/__init__.py
from flask import Flask
from flask_mail import Mail
from PORTIFOLIO.config import Config

mail = Mail()

def create_app():

    app = Flask(__name__)

    app.config.from_object(Config)
    mail.init_app(app)
    
    from .IndexPage.routes import indexPage
    from .WorkPage.routes import workPage
    from .AboutPage.routes import aboutPage
    from .ContactPage.routes import contactPage


    app.register_blueprint(indexPage)
    app.register_blueprint(workPage)
    app.register_blueprint(aboutPage)
    app.register_blueprint(contactPage)

    return app

PORTIFOLIO/templates/About.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>My Work</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body id="bodyWork" class="fullpage slide-up">
    <!-- NAV starts -->
    <div class="navspace">
      <div class="nav-line"></div>
      <div class="TWicon">
        <a href="{{ url_for('indexPage.home') }}">HOME</a>
      </div>
      <div class="copyright">© | 2024</div>
    </div>
    <!-- TITLE starts -->
    <div class="division">
      <div class="Abouttitle animated-textUp">About</div>
      <img
        src="static/uploads/Photo.jpg"
        alt="Photo"
        width="370"
        height="500"
        class="photoadjust"
      />
    </div>
    <div class="AboutSubtitle">
      Hi! My name is Karinna , I'm a problem solver but also a maker.
    </div>
    <div class="selfDescription">
      A lover of technology and a logical thinker, I come from an architecture
      background where I had the pleasure of working for two years. I discovered
      that architecture wasn't my passion, and I wanted more. I moved to America
      for a new challenge in my life and immersed myself in a Computer
      Information Systems college. I became the first person in my family to
      earn an American college degree and discover new skills. I was solving
      problems, and my past career in architecture helped me get where I am
      today. I took advantage of learning Python, HTML, CSS, JavaScript, and
      React Native, and implemented my design mindset into my software
      development. My logical thinking allowed me to find the most efficient
      ways to complete tasks. Everything I have done, small or big, has been a
      vital stepping stone to where I am today.
      <br /><br />
      Known as NurVIX on the internet, I started my streaming channel at the
      beginning of COVID-19. What began as a hobby became much more. I combined
      my passion for tech with my love of making connections. I started playing
      video games and ended up splitting my time coding with my community, where
      we all share knowledge and push each other forward. With a lot of hard
      work and time invested, I grew a channel that now reaches 3,500 followers
      and was fortunate enough to build an awesome and supportive community
      worldwide.
      <br /><br />
      As a Jiu-jitsu lover, aside from technology, I have a passion for martial
      arts. It is a part of me where I learn every day to be humble, respectful,
      and grateful. It teaches me resilience, efficiency, and critical thinking,
      which I constantly implement in my daily life.
      <br /><br />
      You will probably hear me say a lot:
      <br /><br />
      "We got this!"
      <br /><br />
    </div>
    <div class="divSubTitles">
      <div class="subTitles">Experience</div>
      <span class="skillsdescription">
        - Associates in Information technology
        <br />
        - Bachelor in Computer Information System
        <br />
        - 4 years in Software Development, Web Design, SEO Strategy, Mobile
        Devices
        <br />
        <br />
        Within these 4 years, I have:
        <br />
        <br />
        - 4 years experience in Software designing
        <br />
        - 3 years experience in Webflow Development
        <br />
        - 3 years in Mobile Devices
      </span>
      <div class="subTitles">Skills</div>
      <span class="skillsdescription">
        Technical Skills:
        <br />
        <br />
        UI/UX Design / Strategy / Product Management / Mobile Device
        Architecture / Design Sprints / Python / HTML and CSS / React Native /
        Webflow Development
        <br />
        <br />
        Personal Skills:
        <br />
        <br />
        Photography / Jiu jitsu / Guitar / Archery / Chess / Cooking
      </span>
      <div class="buttonbox">
        <a
          href="../static/uploads/Karinna Rocha Resume.pdf"
          target="_blank"
          class="button w-button"
          >My CV</a
        >
      </div>
    </div>
  </body>
</html>

PORTIFOLIO/templates/Contact.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>CONTACT ME</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body id="bodyAIBeans" class="fullpage">
    <div class="navspace">
      <div class="nav-line"></div>
      <div class="TWicon">
        <a href="{{ url_for('indexPage.home') }}">HOME</a>
      </div>
      <div class="copyright">© | 2024</div>
    </div>
    <div class="ContactTitle">Contact me!</div>
    <div class="ContactContent">The best way to get connected with me!</div>
    <div class="contactForm">
      <form action="{{ url_for('contactPage.contact') }}" method="POST">
        <label for="email">Email</label>
        <input type="email" id="email" name="email" required />

        <label for="subject">Subject</label>
        <input type="text" id="subject" name="subject" required />

        <label for="message">Message</label>
        <textarea
          id="message"
          name="message"
          rows="4"
          cols="50"
          required
          class="messagebox"
        ></textarea>

        <button class="button w-button" type="submit">Send Email</button>
      </form>
    </div>
    {% with messages=get_flashed_messages(with_categories=true) %} {% if
    messages %}
    <ul>
      {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %}
  </body>
</html>

PORTIFOLIO/templates/Work.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>My Work</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body id="bodyWork" class="fullpage">
    <!-- NAV starts -->
    <div class="navspace">
      <div class="nav-line"></div>
      <div class="TWicon">
        <a href="{{ url_for('indexPage.home') }}">HOME</a>
      </div>
      <div class="copyright">© | 2024</div>
    </div>
    <!-- TITLE starts -->
    <div class="ExpertiseSession animate-on-scroll">
      <div class="experienceTitle">MY EXPERTISE</div>
      <div class="divisionExper">
        <div class="expertisetitle">Back-end Development</div>
        <div class="expertisecontent">
          Experience in Python backend Development using Flask and Django
          Frameworks.
        </div>
        <div class="expertisetitle">Front-end Design</div>
        <div class="expertisecontent">
          Passionate about design in general, experience on HTML, CSS, and React
          Native.
        </div>
        <div class="expertisetitle">Mobile App</div>
        <div class="expertisecontent">
          Hybrid mobile apps are my way to go on Flutterflow framework.
        </div>
      </div>
    </div>
    <div class="WorkTitlesSession animate-on-scroll">
      <div class="divisionWork">
        <div class="myWork">
          <div>My work</div>
        </div>
        <div class="vertical-line fadein"></div>
        <div class="Worklist">
          <a class="workTitle" data-scroll="nurvix">NURVIX</a><br />
            Web development</span
          ><br />
          <a class="workTitle" data-scroll="signup">SIGN UP</a
          ><br /><span> Web Development</span><br />
          <a class="workTitle" data-scroll="fitness">FITNESS</a
          ><br /><span> Web Development</span><br />
          <a class="workTitle" data-scroll="aibeans">AIBEANS</a
          ><br /><span> Mobile Development</span><br />
          <a class="workTitle" data-scroll="jiujitsu">JIU-JITSU</a
          ><br /><span> Photopraphy</span>
        </div>
      </div>
    </div>
    <div class="ImageSession">
      <div class="experienceTitle">Web development</div>
      <div class="ImageContainer animate-on-scroll" data-section="nurvix">
        <img
          src="../static/uploads/nurvix_page.JPG"
          alt="NurVIX Page"
          class="imageWebsite"
        />
        <p class="image__overlay hoverOverImages">
          <span>NurVIX - Full stack </span>
          <br />
          Specs: Python (Flask), HTML, CSS <br />Deployed: Godaddy
          <a href="https://nurvix.live" target="_blank">NurVI X website</a>
        </p>
      </div>
      <div class="ImageContainer animate-on-scroll" data-section="signup">
        <img
          src="../static/uploads/Mercy_page.JPG"
          alt="Sign Up Page"
          class="imageWebsite"
        />
        <p class="image__overlay hoverOverImages">
          <span>Sign Up Registration - Full Stack</span>
          <br />
          <span>Specs: Python(Django), HTML, CSS</span><br />
          <span>Database: SQLite Built in</span>
        </p>
      </div>
      <div class="ImageContainer animate-on-scroll" data-section="fitness">
        <img
          src="../static/uploads/Daniellysfitness.PNG"
          alt="Fitness Page"
          class="imageWebsite"
        />
        <div class="image__overlay hoverOverImages">
          <span>Danielly's Fitness - Front end</span>
          <br />
          <p>Specs: PHP, HTML, CSS <br />Deployed: Wordpress</p>
          <a href="https://daniellysfitness.com" target="_blank"
            >Danielly's Fitness website</a
          >
        </div>
      </div>
    </div>
    <div class="mobileappSession animate-on-scroll" data-section="aibeans">
      <div class="experienceTitle">Mobile Application</div>
      <div class="AppSession">
        <video class="VideoAIBeans" loop autoplay muted>
          <source src="../static/uploads/AIBEANS.mov" type="video/mp4" />
        </video>
        <div class="AIBeansbox">
          <div class="AIBeansdescription fade-in">
            <p>
              <span>AIBeans - Full Stack</span><br /><br />
              <span>
                Specs:<br />
                Pyton, React Native</span
              >
              <br />Deployed: <br />Heroku, Apple Store <br>
              (Test Mode)
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="PhotographySession animate-on-scroll" data-section="jiujitsu">
      <div class="experienceTitle">Photography</div>
      <div class="photographygalery">Coming soon!</div>
    </div>
  </body>
</html>
<script>
  document.addEventListener("DOMContentLoaded", () => {
    const elementsToAnimate = document.querySelectorAll(".animate-on-scroll");

    function setOpacity() {
      elementsToAnimate.forEach(element => {
        const rect = element.getBoundingClientRect();
        const elementTop = rect.top;
        const elementHeight = rect.height;
        const windowHeight = window.innerHeight;

        if (elementTop >= 0 && elementTop <= windowHeight) {
          // Calculate the ratio of the element visible in the viewport
          const visibility = Math.min((windowHeight - elementTop) / elementHeight, 1);
          element.style.opacity = visibility;
        } else if (elementTop < 0) {
          // When scrolling past the element
          const visibility = Math.max(1 - Math.abs(elementTop) / elementHeight, 0);
          element.style.opacity = visibility;
        } else {
          element.style.opacity = 0;
        }
      });
    }

    // Smooth scrolling for links
    document.querySelectorAll("a[data-scroll]").forEach((link) => {
      link.addEventListener("click", function (e) {
        e.preventDefault();
        const section = this.getAttribute("data-scroll");
        const target = document.querySelector(
          `.ImageContainer[data-section="${section}"]`
        );
        if (target) {
          target.scrollIntoView({ behavior: "smooth" });
        }
      });
    });

    window.addEventListener("scroll", setOpacity);
    setOpacity(); // Set initial opacity based on current scroll position
  });
</script>

PORTIFOLIO/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>NurVIX</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body class="fullpage sandbackground">
    <!-- NAV starts -->
    <div class="navspace navspace.dark">
      <div class="nav-line"></div>
      <div>
        <a href="https://www.linkedin.com/in/karinnarocha/" target="_blank"
          >LI</a
        >
      </div>
      <div>
        <a href="https://github.com/karinnarocha" target="_blank">GH</a>
      </div>
      <div>
        <a href="https://x.com/_nurvix" target="_blank">TW</a>
      </div>
      <div>© | 2024</div>
    </div>

    <!-- TITLE starts -->
    <header>
      <a
        href="https://www.twitch.tv/nurvix"
        class="nurvixHeader animationfading"
        >NurVIX</a
      >
      <div class="karinnaHeader animationfading">Karinna Rocha</div>
    </header>

    <!-- Body starts -->
    <div class="developerHeader animationfading">
      <div>Software Developer</div>
    </div>
    <div class="Menu-link">
      <div>
        <a href="{{ url_for('workPage.workpage') }}">Work</a>
      </div>
      <div>●</div>
      <div>
        <a href="{{ url_for('aboutPage.aboutpage') }}">About</a>
      </div>
      <div>●</div>
      <div>
        <a href="{{ url_for('contactPage.contact') }}">Contact</a>
      </div>
    </div>
  </body>
</html>